using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Nodes;
using FluentAssertions;
using MongoDB.Bson;
using OxQL.Core.Binding;
using OxQL.Core.Engine;
using OxQL.Core.Models;
using OxQL.IntegrationTests.Fleet;
using OxQL.IntegrationTests.Harness;
using OxQL.Model;
using OxQL.Mongo;
using Xunit;

namespace OxQL.IntegrationTests.Suites.Explain;

/// <summary>
/// The studio's describe plan (<c>Fixtures/describe-plan.json</c>, generated by the frontend's
/// <c>describe-plan.spec.ts</c>): every envelope the studio sends while a user builds A1–A5 on the
/// fleet, explained by the fleet's engines in process. Each one binds (<c>valid: true</c>), every
/// describe entry is answered without an error, and every part at another service — the remote
/// describes and the remote check of continued stages — is answered by its owner's internal
/// explain, so no <c>REMOTE_UNCHECKED</c> note is left. Nothing is read from a database: explain
/// never executes, and the fleet's entities carry no addons the plan reaches.
/// </summary>
[Trait("Category", "Integration")]
public class ExplainDescribePlanTests
{
    internal static readonly Lazy<JsonObject> Plan = new(() => JsonNode.Parse(File.ReadAllText(PlanPath()))!.AsObject());

    /// <summary>The (step, describe id) pairs of the plan that focus an alias the step's query does not create yet.</summary>
    private static readonly HashSet<(string Step, string Describe)> AheadOfItsStage = [("A5.14", "focus")];

    private static string PlanPath([CallerFilePath] string source = "") =>
        Path.Combine(Path.GetDirectoryName(source)!, "Fixtures", "describe-plan.json");

    public static TheoryData<string> Steps()
    {
        var steps = new TheoryData<string>();

        foreach (var scenario in Plan.Value["scenarios"]!.AsArray())
            foreach (var step in scenario!["steps"]!.AsArray())
                steps.Add(step!["id"]!.GetValue<string>());

        return steps;
    }

    [Fact]
    public void X20_the_plan_holds_the_studios_73_steps_over_six_scenarios()
    {
        Plan.Value["scenarios"]!.AsArray().Select(scenario => scenario!["id"]!.GetValue<string>()).Should().Equal("A1", "A2", "A2b", "A3", "A4", "A5");
        Steps().Cast<object[]>().Should().HaveCount(73);
    }

    [Theory]
    [MemberData(nameof(Steps))]
    public async Task X21_every_envelope_of_the_describe_plan_binds_and_every_describe_is_answered(string id)
    {
        var envelope = Plan.Value["scenarios"]!.AsArray()
            .SelectMany(scenario => scenario!["steps"]!.AsArray())
            .Single(step => step!["id"]!.GetValue<string>() == id)!["envelope"]!;
        var request = JsonSerializer.Deserialize<ExplainRequest>(envelope.ToJsonString(), OxQLJson.Wire)!;
        var fleet = new InProcessFleet();

        var answer = await fleet.ExplainAsync(request);

        answer.Valid.Should().BeTrue(string.Join("; ", answer.Errors.Select(error => $"{error.Code}@{error.Stage} {error.Path}: {error.Message}")));
        answer.Describe.Should().HaveCount(request.Describe.Count);

        foreach (var described in answer.Describe.Select(node => node.AsObject()))
        {
            var what = described.ToJsonString();

            // The plan's one focus on an alias its query does not have yet: A5.14 describes lineTour
            // before the stage that creates it is in the envelope. The answer says so.
            if (AheadOfItsStage.Contains((id, described["id"]!.GetValue<string>())))
            {
                described["error"]!["code"]!.GetValue<string>().Should().Be(Codes.UnknownPath, what);
                continue;
            }

            described["error"].Should().BeNull(what);
            described["root"].Should().NotBeNull(what);
            described["truncated"]!.GetValue<bool>().Should().BeFalse(what);
            described["children"]!.AsArray().Should().NotBeEmpty(what);
        }

        answer.Notes.Where(note => note.Code == Notes.RemoteUnchecked).Should().BeEmpty("every owner answers in process");
    }

    [Fact]
    public async Task X22_a_describe_under_a_remote_union_alias_is_answered_by_both_owners_targets_and_marked_forwarded()
    {
        var step = Plan.Value["scenarios"]!.AsArray()
            .SelectMany(scenario => scenario!["steps"]!.AsArray())
            .First(step => step!["envelope"]!["describe"]!.AsArray().Any(entry => entry!["prefix"]?.GetValue<string>() == "sourceParent"))!;
        var request = JsonSerializer.Deserialize<ExplainRequest>(step["envelope"]!.ToJsonString(), OxQLJson.Wire)!;

        var answer = await new InProcessFleet().ExplainAsync(request);
        var described = answer.Describe.Select(node => node.AsObject()).Single(entry => entry["prefix"]?.GetValue<string>() == "sourceParent");

        described["forwarded"]!.GetValue<bool>().Should().BeTrue();
        described["root"]!["node"]!.GetValue<string>().Should().Be("remote");
        described["root"]!["entities"]!.AsArray().Select(node => node!.GetValue<string>()).Should().Contain(["transport.shipment", "transport.tour"]);

        var children = described["children"]!.AsArray().Select(node => node!.AsObject()).ToList();

        children.Should().Contain(child => child["path"]!.GetValue<string>() == "sourceParent.shipmentNumber");
        children.Should().OnlyContain(child => !child["sortable"]!.GetValue<bool>() && !child["unwindable"]!.GetValue<bool>(), "the owner's rows are joined after the page here");
    }

    /// <summary>The fleet's engines side by side, each the owner of its service's entities, explaining for one another in process as the internal explain route would.</summary>
    internal sealed class InProcessFleet : IRemoteQueryClient
    {
        private readonly Dictionary<string, MongoQueryEngine> engines = new(StringComparer.Ordinal);
        private readonly EngineDirect direct = new(LabService.Ledger.Model);

        public InProcessFleet()
        {
            foreach (var service in LabService.All)
                engines[service.Key] = new MongoQueryEngine(new StaticEntityModelProvider(service.Model), new NoRunner(), direct.Cursors, direct.Options(), this);
        }

        public async Task<ExplainResult> ExplainAsync(ExplainRequest request)
        {
            var service = request.Query.EntityType.Split('.')[0];
            var outcome = await engines[service].ExplainAsync(request, direct.Context());

            return outcome.Should().BeOfType<ExplainOutcome.Success>(outcome is ExplainOutcome.Refused refused ? EngineDirect.Describe(refused.Refusal) : "").Subject.Result;
        }

        public bool IsConfigured(string serviceKey) => engines.ContainsKey(serviceKey);

        public Task<bool> IsReachableAsync(string serviceKey, CancellationToken cancellationToken) => Task.FromResult(IsConfigured(serviceKey));

        public Task<BatchResponse> BatchAsync(string serviceKey, BatchRequest request, TimeSpan budget, CancellationToken cancellationToken) =>
            throw new InvalidOperationException("Explain never runs a batch.");

        /// <summary>The owner's internal explain: its engine under the forwarded organisation, as an internal call, answered as wire JSON.</summary>
        public async Task<JsonObject?> ExplainAsync(string serviceKey, ExplainRequest request, TimeSpan budget, CancellationToken cancellationToken)
        {
            var sent = JsonSerializer.Deserialize<ExplainRequest>(JsonSerializer.Serialize(request, OxQLJson.Wire), OxQLJson.Wire)!;
            var outcome = await engines[serviceKey].ExplainAsync(sent, direct.Context() with { Internal = true }, cancellationToken);

            return outcome is ExplainOutcome.Success success ? JsonSerializer.SerializeToNode(success.Result, OxQLJson.Wire)!.AsObject() : null;
        }
    }

    private sealed class NoRunner : IAggregateRunner
    {
        public Task<IReadOnlyList<BsonDocument>> AggregateAsync(EntityDef entity, IReadOnlyList<BsonDocument> stages, AggregateRunOptions options, CancellationToken cancellationToken) =>
            throw new InvalidOperationException("Explain never runs an aggregate.");
    }
}
